# Generated by Django 3.1.7 on 2021-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='begin_heating',
            field=models.DateField(default=1988),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.TextField(default='0 0 0 0 0 0 0 0 0 0 0 0'),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_heating',
            field=models.DateField(default=1988),
        ),
        migrations.AlterField(
            model_name='data',
            name='project_type',
            field=models.CharField(choices=[('M', 'ежемесячные данные')], default='M', max_length=1),
        ),
    ]
