# Generated by Django 3.1.7 on 2021-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210328_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='begin_heating',
            field=models.DateField(default='2020-10-22'),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_heating',
            field=models.DateField(default='2020-10-22'),
        ),
    ]
