# Generated by Django 3.1.7 on 2021-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210402_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='begin_heating',
            field=models.DateField(default='2021-10-15'),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_heating',
            field=models.DateField(default='2021-04-15'),
        ),
    ]
